apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eshop-webhooks-web
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    repoURL: 'https://github.com/mvktsk/eShopOnContainers'
    path: ./deploy/k8s/helm/webhooks-web
    targetRevision: dev
    helm:
      valueFiles:
        - ../app.yaml
        - ../inf.yaml
        - ../ingress_values.yaml
        - ../ingress_values_linkerd.yaml
      values: |-
        app:
          name: eshop
        inf:
          k8s:
            dns: eshop.874624fb8c3c4410b1bd.centralus.aksapp.io
            local: false
        tls:
          enabled: false
        mesh: 
          enabled: false
        ingress:
          hosts: {eshop.874624fb8c3c4410b1bd.centralus.aksapp.io}
        image:
          tag: linux-dev
          pullPolicy: Always
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: eshop
